### ISSUE TITLE
Crash when used with Thaumcraft

### ISSUE THREAD

**Issue by madsmith** [ynohtna92/WeepingAngels#13]
I'm trying to track down the cause of this but I'm not familiar with Minecraft internals and Forge's API.

I've been getting crashes when using this mod together with Thaumcraft 3.  Assuming I can even login, I get a client crash as I travel through the world.  

Here's a the error I'm getting.

The client side crashes when it attempts to convert a thaumcraft.common.entities.EntitySpecialItem into an EntityLiving when it receives a MobSpawn packet.  

[quote]2013-02-28 06:09:29 [INFO] [STDERR] t: Ticking screen
2013-02-28 06:09:29 [INFO] [STDERR]  at net.minecraft.client.Minecraft.l(Minecraft.java:1546)
2013-02-28 06:09:29 [INFO] [STDERR]  at net.minecraft.client.Minecraft.J(Minecraft.java:848)
2013-02-28 06:09:29 [INFO] [STDERR]  at net.minecraft.client.Minecraft.run(Minecraft.java:773)
2013-02-28 06:09:29 [INFO] [STDERR]  at java.lang.Thread.run(Unknown Source)
2013-02-28 06:09:29 [INFO] [STDERR] Caused by: java.lang.ClassCastException: thaumcraft.common.entities.EntitySpecialItem cannot be cast to md
2013-02-28 06:09:29 [INFO] [STDERR]  at ayh.a(NetClientHandler.java:895)
2013-02-28 06:09:29 [INFO] [STDERR]  at co.a(SourceFile:87)
2013-02-28 06:09:29 [INFO] [STDERR]  at cg.b(TcpConnection.java:458)
2013-02-28 06:09:29 [INFO] [STDERR]  at ayh.d(NetClientHandler.java:240)
2013-02-28 06:09:29 [INFO] [STDERR]  at ayk.c(GuiConnecting.java:49)
2013-02-28 06:09:29 [INFO] [STDERR]  at net.minecraft.client.Minecraft.l(Minecraft.java:1539)
2013-02-28 06:09:29 [INFO] [STDERR] ... 3 more[/quote]

Here's a copy of my ForgeModLoader log: https://dl.dropbox.com/u/39916180/Minecraft/ForgeModLoader-client-0.log

**Comment by TimoMeijer** [comment]
According to your log it's more likely to do with Xycraft or NEI, as it crashes after that loads it's configs.
When using this many mods, please try again with only Thaumcraft and Weeping Angels enabled, and try if you can reproduce the error.

I myself have been using them together for about a month on a server without any issue.

It might also be worth checking your entity IDs don't conflict.

**Comment by madsmith** [comment]
I spent some time moving mods out of the mods and coremods folder, deleting the world and regenerating to see what I could "exclude" from this issue.

I'm able to repro this issue with just forge, MCP, FML, Thaumcraft 3.0.3 and weeping angels 158.

ForgeModLoader log of client error

https://dl.dropbox.com/u/39916180/Minecraft/TAWA/ForgeModLoader-client-0.log

I packaged up the server and client and the world that last triggered a crash.
https://dl.dropbox.com/u/39916180/Minecraft/TAWA/TC-WA_Crash.zip

That said, it's a fricking race condition that is becoming increasingly hard to reproduce.  It is a bug that only appears to happen in client connecting to server configurations.  When I'm running the client and the server on the same host, I am hard pressed to recreate the issue (so far like 1 in 25 tries). Normally, I run the server on my mac and connect to it from the client running on a PC going through my public IP and back into my server.  There's some data transmission that's happening that's getting garbled and trigger the above error.

**Comment by madsmith** [comment]
Think I might know why this is happening. Neither thaumcraft nor weeping angels uses the cfg entity I'd when registering their entities globally and instead request an id from forge. I actually rename the jar file on the client side to simply WeepingAngels.jar so I can patch in updates. On the server, I leave the version number in the filename. Since WA prefixes its version while Thaumcraft suffixes it, this results in an inverted lexical ordering. I bet WA loads before Thaumcraft on the server and after on the client. There is a config syncing phase when loading in but this mob spawn packet must be generating before the client can fix its ids. 

And the problem disappeared on me because I renamed the jar files before zipping up the server client directories. Which, if I'm right, inadvertently fixed the problem. 

Btw, it's totally weird that the angel ent ID is unused. Thaumcraft seems to eventually pass in the ids when registering itself as the owner of the entities. 

I'll test this theory tomorrow and let you know if renaming the files is the solution.

**Comment by TimoMeijer** [comment]
Thanks for reporting and narrowing it down this much.
I'm quite new to the WA development, but that sounds like a probable cause.
I'll take a look when I have some time.
And thanks once again!

**Comment by madsmith** [comment]
Yup, on the server, I see this

2013-03-03 16:48:56 [INFO] [Forge] Activating mod Forge
2013-03-03 16:48:56 [INFO] [WeepingAngelsMod] Activating mod WeepingAngelsMod
2013-03-03 16:48:56 [INFO] [Thaumcraft] Activating mod Thaumcraft

when the mods files names are left unchanged (147-158WeepingAngels.zip and Thaumcraft3.0.3.zip)

On the client I see this

2013-03-03 16:49:26 [INFO] [Forge] Activating mod Forge
2013-03-03 16:49:26 [INFO] [Thaumcraft] Activating mod Thaumcraft
2013-03-03 16:49:26 [INFO] [WeepingAngelsMod] Activating mod WeepingAngelsMod

where I truncate the mod names to remove versioning information (Thaumcraft.zip and WeepingAngels.zip) so that a mod loader like the technic launcher can patch updates over existing files.

both mods invoke the EntityRegistry to get an assigned entity id
EntityRegistry.registerGlobalEntityID(EntityWeepingAngel.class, "Weeping Angel", ModLoader.getUniqueEntityId(), 0x00000, 0xffffff);

Since they're happening in inverted order, the ids are being flipped.  

Now Thaumcraft does eventually use the entity id unlike weeping angels (decompile thaumcraft and see thaumcraft.common.Config)

/\*  750 _/     EntityRegistry.registerGlobalEntityID(EntitySpecialItem.class, "entSpecialItem", EntityRegistry.findGlobalUniqueEntityId());
/_  751 */     EntityRegistry.registerModEntity(EntitySpecialItem.class, "entSpecialItem", entSpecialItemId, Thaumcraft.instance, 64, 20, true);

the latter of which seems to only be used in Forge.

Anyway, not sure if there's a bug here to be fixed.  Probably be nice to either remove or implement the entity id depending on how Forge is supposed to work.  Moving the version information in the build result to after the mod name would be advisable but that's not really a bug.  I'll fix my packaging so that my mods will load in the same order.

Feel free to close this out.

**Comment by GotoLink** [comment]
The fix is commented out in line 102 of the main class.

**Comment by GotoLink** [comment]
http://www.minecraftforum.net/topic/1417041-mod-entity-problem-updated-with-forge/page__st__140#entry18822284
This post explain how it works.
